import type { FastifyInstance } from "fastify";
import { nanoid } from "nanoid";
import { z } from "zod";
import { requireActor } from "../auth/auth.js";
import { forbidden } from "../errors.js";
import { withSpan } from "../observability/tracing.js";
import { PrismaAgentRegistryResolver } from "./registryResolver.js";
import { RuleBasedPlannerProvider } from "./workflowPlanner.js";
import { writeAgentDecisionAudit } from "./agentAudit.js";
import type { AgentPlan } from "./agentTypes.js";

const agentRequestSchema = z.object({
  projectId: z.string().min(1),
  message: z.string().min(1),
  context: z.record(z.unknown()).default({})
});

function actor(request: any) {
  if (!request.actor) throw forbidden("Authenticated actor required");
  return request.actor;
}

function artifactsFor(system: string) {
  return [
    { name: "requirements.md", kind: "sdd_requirements", content: `# ${system} Requirements\n\nGenerated by the self-service agent. Fill in business goal, target users, tools, auth, data classification, approvals, audit, observability, and acceptance criteria.\n` },
    { name: "design.md", kind: "sdd_design", content: `# ${system} Design\n\nADK/MDK apps call MCP Gateway. Gateway enforces auth, RBAC, policy, audit, metrics, traces, and secret references before routing to the connector runtime.\n` },
    { name: "tasks.md", kind: "sdd_tasks", content: `# ${system} Tasks\n\nImplement tools, tests, manifest validation, docs, security review, registration, deployment, and approval tasks.\n` },
    { name: "connector.yaml", kind: "connector_manifest", content: `id: ${system}-mcp-connector\nstatus: draft\nowner_team: service-management-platform\nruntime_owner: service-management-platform\nsecurity_reviewer: security-platform\n` },
    { name: "policy.yaml", kind: "policy", content: "defaults:\n  write_tools: approval_required\n  audit_all_calls: true\n" },
    { name: "registration-request.yaml", kind: "registration_request", content: `desired_system: ${system}\nstatus: draft\nsource: self_service_agent\n` }
  ];
}

function requestedToolsFor(plan: AgentPlan) {
  if (plan.tool) return [plan.tool];
  if (plan.connector === "servicenow" || plan.system === "servicenow") {
    return ["servicenow.search_incidents", "servicenow.get_incident", "servicenow.create_incident", "servicenow.update_incident"];
  }
  if (plan.connector === "jira" || plan.system === "jira") return ["jira.search_issues"];
  return [`${plan.system ?? "connector"}.search`];
}

async function ensurePendingConnectorAccessRequest(app: FastifyInstance, request: any, projectId: string, connectorId: string) {
  const existingAccess = await app.db.connectorAccessRequest.findUnique({
    where: { projectId_connectorId: { projectId, connectorId } }
  });
  if (existingAccess) return existingAccess;
  return app.db.connectorAccessRequest.create({
    data: { id: nanoid(), projectId, connectorId, status: "pending", requestedBy: actor(request).id }
  });
}

async function createOrReuseAccessRequest(app: FastifyInstance, request: any, plan: AgentPlan, projectId: string) {
  const connectorId = plan.connector ?? plan.system;
  if (!connectorId) return undefined;
  const existing = await app.db.selfServiceRequest.findFirst({
    where: {
      type: "existing_connector_access",
      projectId,
      connectorId,
      status: { in: ["requested", "submitted", "security_review", "platform_review", "approved"] }
    },
    orderBy: { createdAt: "desc" }
  });
  if (existing) {
    await ensurePendingConnectorAccessRequest(app, request, projectId, connectorId);
    return existing;
  }
  const created = await app.db.selfServiceRequest.create({
    data: {
      id: nanoid(),
      type: "existing_connector_access",
      source: "agent",
      status: "requested",
      requesterId: actor(request).id,
      projectId,
      team: "ai-platform",
      connectorId,
      requestedTools: requestedToolsFor(plan),
      readOrWriteIntent: requestedToolsFor(plan).some((tool) => /create|update|transition|comment/.test(tool)) ? "read_write" : "read",
      businessJustification: "Created by self-service agent from natural language request.",
      dataClassification: connectorId === "jira" || connectorId === "servicenow" ? "confidential" : "internal",
      expectedVolume: "local MVP",
      approvalRequired: true,
      approvers: ["ai-platform", "security-platform"],
      metadata: { agentIntent: plan.intent, workflow: plan.workflow }
    }
  });
  await ensurePendingConnectorAccessRequest(app, request, projectId, connectorId);
  return created;
}

async function createOrReuseConnectorRequest(app: FastifyInstance, request: any, plan: AgentPlan, projectId: string) {
  const system = plan.system ?? "custom-system";
  const connectorId = plan.connector ?? `${system}-mcp-connector`;
  const existing = await app.db.selfServiceRequest.findFirst({
    where: {
      type: "new_connector_registration",
      connectorId,
      status: { in: ["draft", "submitted", "security_review", "platform_review", "approved"] }
    },
    include: { artifacts: true },
    orderBy: { createdAt: "desc" }
  });
  if (existing) return existing;
  return app.db.selfServiceRequest.create({
    data: {
      id: nanoid(),
      type: "new_connector_registration",
      source: "agent",
      status: "draft",
      requesterId: actor(request).id,
      projectId,
      team: "service-management-platform",
      connectorId,
      desiredSystem: system,
      requestedTools: requestedToolsFor(plan),
      readOrWriteIntent: "read_write",
      businessJustification: "Created by self-service agent using Spec-Driven Development.",
      dataClassification: system === "servicenow" || system === "jira" ? "confidential" : "internal",
      expectedVolume: "local MVP",
      approvalRequired: true,
      approvers: ["ai-platform", "security-platform"],
      ownerTeam: "service-management-platform",
      runtimeOwner: "service-management-platform",
      securityReviewer: "security-platform",
      deploymentMode: "remote",
      metadata: { sdd: true, agentIntent: plan.intent, workflow: plan.workflow },
      artifacts: {
        create: artifactsFor(system).map((artifact) => ({ id: nanoid(), ...artifact }))
      }
    },
    include: { artifacts: true }
  });
}

async function invokeGatewayThroughPlatform(app: FastifyInstance, request: any, plan: AgentPlan, projectId: string) {
  if (!plan.connector || !plan.tool) return undefined;
  const authorization = request.headers.authorization;
  const response = await app.inject({
    method: "POST",
    url: `/gateway/connectors/${encodeURIComponent(plan.connector)}/tools/${encodeURIComponent(plan.tool)}/invoke`,
    headers: {
      ...(authorization ? { authorization } : {}),
      "content-type": "application/json",
      "x-correlation-id": request.id
    },
    payload: { projectId, input: plan.input ?? {} }
  });
  const parsedBody = response.body ? JSON.parse(response.body) : {};
  return { statusCode: response.statusCode, ok: response.statusCode >= 200 && response.statusCode < 300, body: parsedBody };
}

export async function registerSelfServiceAgentRoutes(app: FastifyInstance) {
  app.post("/agent/request", { preHandler: requireActor }, async (request: any) => {
    const body = agentRequestSchema.parse(request.body);
    const planner = new RuleBasedPlannerProvider(new PrismaAgentRegistryResolver(app));
    const plan = await withSpan("agent.workflow_plan", {
      request_id: request.id,
      project_id: body.projectId
    }, () => planner.plan({ projectId: body.projectId, message: body.message, context: body.context, actor: actor(request) }));

    let requestRecord: { id: string; status?: string } | undefined;
    let gatewayResult: Awaited<ReturnType<typeof invokeGatewayThroughPlatform>> | undefined;
    let registryResult: unknown;

    if (plan.intent === "existing_connector_access_request") {
      requestRecord = await createOrReuseAccessRequest(app, request, plan, body.projectId);
      plan.requestId = requestRecord?.id;
      plan.status = requestRecord?.status ?? "requested";
    } else if (plan.intent === "new_connector_onboarding" || plan.intent === "generated_connector_repo_request") {
      requestRecord = await createOrReuseConnectorRequest(app, request, plan, body.projectId);
      plan.requestId = requestRecord?.id;
      plan.status = requestRecord?.status ?? "draft";
    } else if (plan.intent === "connector_tool_execution") {
      gatewayResult = await invokeGatewayThroughPlatform(app, request, plan, body.projectId);
      if (gatewayResult?.ok) {
        plan.decision = "allowed";
        plan.nextStep = "gateway_invocation_completed";
      } else if (gatewayResult?.statusCode === 409 && plan.decision === "approval_required") {
        plan.nextStep = "approval_request_created";
      } else if (gatewayResult) {
        plan.nextStep = "gateway_denied";
      }
      plan.gatewayResult = gatewayResult?.body;
      plan.requestId = gatewayResult?.body?.requestId ?? request.id;
    } else if (plan.intent === "registry_lookup") {
      const connectors = await app.db.connector.findMany({
        select: { id: true, name: true, status: true, riskLevel: true, dataClassification: true },
        orderBy: { id: "asc" },
        take: 50
      });
      registryResult = { connectors };
    }

    await writeAgentDecisionAudit(app.db, actor(request), body.projectId, plan, request.id);

    return {
      intent: plan.intent,
      workflow: plan.workflow,
      connector: plan.connector,
      tool: plan.tool,
      system: plan.system,
      decision: plan.decision,
      next_step: plan.nextStep,
      status: plan.status,
      requestId: plan.requestId ?? request.id,
      artifacts: plan.artifacts,
      input: plan.input,
      gateway: gatewayResult?.body,
      registry: registryResult,
      reason: plan.reason
    };
  });
}
