import type { FastifyInstance } from "fastify";
import { nanoid } from "nanoid";
import { z } from "zod";
import { requireActor } from "../auth/auth.js";
import { writeAuditEvent } from "../audit/audit.service.js";
import { forbidden } from "../errors.js";

function actor(request: any) {
  if (!request.actor) throw forbidden("Authenticated actor required");
  return request.actor;
}

const intakeSchema = z.object({
  request: z.string().min(1),
  projectId: z.string().min(1).default("ai-platform-demo"),
  team: z.string().min(1).default("service-management-platform"),
  ownerTeam: z.string().min(1).default("service-management-platform"),
  expectedVolume: z.string().default("500 requests/day")
});

function inferSystem(text: string) {
  const lower = text.toLowerCase();
  if (lower.includes("jira")) return "jira";
  if (lower.includes("servicenow") || lower.includes("service now")) return "servicenow";
  if (lower.includes("github")) return "github-enterprise";
  if (lower.includes("slack")) return "slack";
  if (lower.includes("confluence")) return "confluence";
  if (lower.includes("workday")) return "workday";
  return "custom-system";
}

function toolsFor(system: string) {
  if (system === "jira") return ["jira.search_issues"];
  if (system === "servicenow") return ["servicenow.search_incidents", "servicenow.get_incident", "servicenow.create_incident", "servicenow.update_incident"];
  return [`${system}.search`];
}

function artifactsFor(system: string, ownerTeam: string) {
  return [
    {
      id: nanoid(),
      name: "requirements.md",
      kind: "sdd_requirements",
      content: `# ${system} Connector Requirements

## Business Goal

Use ${system} safely from approved ADK/MDK agents through MCP Gateway.

## Target System

${system}

## Users And Personas

- DS / agent developer
- Connector owner: ${ownerTeam}
- Platform admin
- Security reviewer

## Allowed Tools

${toolsFor(system).map((tool) => `- ${tool}`).join("\n")}

## Denied Tools

- Direct credential access
- Unbounded export
- Destructive administration

## Approval Requirements

Write tools require human approval.
`
    },
    {
      id: nanoid(),
      name: "design.md",
      kind: "sdd_design",
      content: `# ${system} Connector Design

ADK/MDK apps call MCP Gateway. MCP Gateway performs auth, RBAC, policy, audit, metrics, and trace propagation before routing to the connector runtime.

\`\`\`mermaid
sequenceDiagram
  participant Agent
  participant Gateway
  participant Policy
  participant Connector
  participant System as ${system}
  Agent->>Gateway: invoke tool
  Gateway->>Policy: evaluate
  Policy-->>Gateway: allowed / approval_required
  Gateway->>Connector: invoke
  Connector->>System: API call or mock
  System-->>Connector: result
  Connector-->>Gateway: safe output
  Gateway-->>Agent: response
\`\`\`
`
    },
    {
      id: nanoid(),
      name: "tasks.md",
      kind: "sdd_tasks",
      content: `# ${system} Connector Tasks

- Confirm registry reuse or new build.
- Implement connector tools.
- Add tests.
- Validate manifest.
- Route to platform/security review.
- Promote through dev, staging, and prod.
`
    },
    {
      id: nanoid(),
      name: "connector.yaml",
      kind: "connector_manifest",
      content: `id: ${system}-mcp-connector
owner_team: ${ownerTeam}
runtime_owner: ${ownerTeam}
security_reviewer: security-platform
status: draft
`
    },
    {
      id: nanoid(),
      name: "policy.yaml",
      kind: "policy",
      content: `defaults:
  write_tools: approval_required
  audit_all_calls: true
`
    },
    {
      id: nanoid(),
      name: "validation-report.md",
      kind: "validation_report",
      content: `# Validation Report

Generated by onboarding agent. Local scaffold and review package are ready for platform/security review.
`
    }
  ];
}

export async function registerOnboardingAgentRoutes(app: FastifyInstance) {
  app.post("/onboarding/agent/intake", { preHandler: requireActor }, async (request: any) => {
    const body = intakeSchema.parse(request.body);
    const desiredSystem = inferSystem(body.request);
    const existing = await app.db.connector.findUnique({ where: { id: desiredSystem }, include: { tools: true } });
    const approved = existing?.status === "approved";
    const requestedTools = approved
      ? existing.tools.slice(0, 2).map((tool) => tool.name)
      : toolsFor(desiredSystem);
    const type = approved ? "existing_connector_access" : "new_connector_registration";
    const created = await app.db.selfServiceRequest.create({
      data: {
        id: nanoid(),
        type,
        source: "agent",
        status: approved ? "requested" : "draft",
        requesterId: actor(request).id,
        projectId: body.projectId,
        team: body.team,
        connectorId: approved ? desiredSystem : `${desiredSystem}-mcp-connector`,
        desiredSystem,
        requestedTools,
        readOrWriteIntent: requestedTools.some((tool) => /create|update|transition|send/.test(tool)) ? "read_write" : "read",
        businessJustification: body.request,
        dataClassification: desiredSystem === "servicenow" || desiredSystem === "jira" ? "confidential" : "internal",
        expectedVolume: body.expectedVolume,
        approvalRequired: true,
        approvers: ["ai-platform", "security-platform"],
        ownerTeam: body.ownerTeam,
        runtimeOwner: body.ownerTeam,
        securityReviewer: "security-platform",
        deploymentMode: approved ? "managed" : "remote",
        metadata: {
          intake: body.request,
          registryCheck: approved ? "reuse_existing_approved_connector" : "new_connector_required",
          recommendedTemplate: desiredSystem === "servicenow" ? "jira-like-issue-tracker" : "generic-rest-api"
        },
        artifacts: approved ? undefined : { create: artifactsFor(desiredSystem, body.ownerTeam) }
      },
      include: { artifacts: true, approvalSteps: true, comments: true }
    });
    await writeAuditEvent(app.db, {
      actorId: actor(request).id,
      actorType: "user",
      projectId: body.projectId,
      action: "onboarding_agent.intake",
      resourceType: "self_service_request",
      resourceId: created.id,
      decision: "allowed",
      reason: "Onboarding agent created guided request",
      reasonCode: "ONBOARDING_AGENT_INTAKE",
      requestId: request.id,
      metadata: { desiredSystem, approvedConnectorFound: approved }
    });
    return {
      request: created,
      recommendation: approved
        ? `Reuse approved connector ${desiredSystem}; create project access request.`
        : `Generate a new ${desiredSystem} connector repo with SDD artifacts and route to platform/security review.`
    };
  });
}
